version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
# loggers:
#   simpleExample:
#     level: DEBUG
#     handlers: [console]
#     propagate: no
root:
  level: DEBUG
  # level: !!python/name:logging.NOTSET
  handlers: [console]
